language: scala
sudo: false
scala:
- 2.10.6
- 2.11.7
script:
- scripts/travis-publish.sh
cache:
  directories:
  - "$HOME/.sbt/0.13/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2d5ea16a2f66f60a590b
    on_success: change
    on_failure: always
    on_start: false
env:
  global:
  - secure: DbdGtV4Tg3BFb5iizdP76Ri39MytHPtJTR7tkfCSWiblVJ63IIub5kiFX+wHVe3usmR65Hyg/cZekBj9OPFomr8CDZegL+JDlUc+/3mpAOYzkjA9XBszQLC3joag2MEbItxWGZ0PQhNSZrcM7eC27zNkteb7hibw6aSnRfJDGlcoqYu7ETBRvNenUtfeBFbVQp5YpcUttQW6actXtCBm1g65ONdkikKLl1M5+yQa29FqhOPHq2Gz+V+TS1Z2pueigBnWNZ3dIf0kY5UpQhfozVpfdFR9wYiiKERwVkBswakff+us1gwEqb0OjHh9UIvgEceJLajoX51b24wArKX0xyePoTwZur1xpB5C1u6mcwTr0hEqWt8agV1LLtzIDw9vaXEE6m3lEq5t7/WD5WaTud9RvDevlS0NIaWLDLLUXmclwV7zNrkZDRfy30ftljUyQQhE5OCDjFkgTTVJGBo4JoYvjJPbLVMqZn9MMYBxoS6ih0k1NTR/bvJ7QtuBEwWwN+4R6rOdVuHIG846up6rG4J4weypzJ50UebzzHYZACRsGko24SJqirup6ROLcvKKptYbmFFGSjUVCPNGGbNwwqZ/zX/p5rFC55P09suYeBI7DjUxip/xJ3p5nvT2avsfaxWy/RdSsa0OkqSFfnQt6VFxKWOM9RqjMlAZIXnqrXQ=
  - secure: AIBM5fCV96EpdeGrrDIzN5+OSaIgXRr8b8SnzUWzDRKLYHMkYMC1b4rggNZhu7EOSUXgDZKLTjLQhW8UposFhsxtvfzsKC/84h7VUQolObpHfsa5u0qg4xMXg2n5bUBwkoisLl8pODVXKCeWttn3jkQjsQ6Nwywm4L3wGTx4wZmCrzX5FMys5WjvDQ5yMgNxVYtXn2igkcgnKxvLWy4cN0tfNRD7nKlJrwftBs8t8H5kaE1SXiFfToxUcri2g1o+7lgIerwuB3lLKAWDaGscDmDEH3YwoGvu/2pTRNgx+38fssNLcxaeFpLajcLPxKm5dJR/1KSgfiQth2+Nu3WJbBGgUAxXmj5UzYrqrrXe4MvMsaMGfaQMBdUSvRrnG+7Luq+V5dcdThBW/Uaa3OJhd1VtOZOew6alsm62leSi/37FSkjrJucPpFfc2FuXHd8es4URpwf6AjgeDCwQFlS6nxhHPpe7PDSVgydrPgD4tdfiTDNRMI6DOsRIQS0NB5dYuotTHWYEH7nRGUjeel9bxgQSuHz1BFd0PPYvZiNsN9nJKm2Q/r38STPM4oSm5c/E+jnmur8oDATJF5hYbYRlgSgreaxawQGE2hpfMLgBRO/xnuVYPQia/xRQTrox3Pb/6REyP31vmwvwoRly2ghNue79ojkL9/goAJlT7sdZ+FI=
